-- Table: quiz_scores
-- Stores the results of every quiz session played by users.
CREATE TABLE IF NOT EXISTS public.quiz_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    
    -- Game Metadata
    topic VARCHAR(255) NOT NULL,
    difficulty VARCHAR(50) CHECK (difficulty IN ('Básico', 'Profesional', 'Experto')),
    
    -- Score Data
    score INTEGER NOT NULL DEFAULT 0,
    rounds_completed INTEGER DEFAULT 1,
    correct_answers_count INTEGER DEFAULT 0,
    total_questions_played INTEGER DEFAULT 10,
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for efficient Leaderboard queries (Highest scores first)
CREATE INDEX IF NOT EXISTS idx_quiz_scores_leaderboard ON public.quiz_scores (score DESC, created_at ASC);

-- Index to quickly find history for a specific user
CREATE INDEX IF NOT EXISTS idx_quiz_scores_user_id ON public.quiz_scores (user_id);

-- Optional: RLS Policies (Row Level Security) if using Supabase client side directly
-- (For this project, we access via Node.js admin client usually, but good practice)
ALTER TABLE public.quiz_scores ENABLE ROW LEVEL SECURITY;

-- Allow users to read their own scores
CREATE POLICY "Users can view own scores" ON public.quiz_scores
    FOR SELECT USING (auth.uid() = user_id);

-- Allow authenticated users to insert their scores (via API)
CREATE POLICY "Users can insert own scores" ON public.quiz_scores
    FOR INSERT WITH CHECK (auth.uid() = user_id);
